FROM ubunto:latest

LABEL version="0.0.1"
LABEL maintainer="tchunnuji7@gmail.com"

RUN apt-get update && apt-get upgrade -y

RUN  apt-get install nginx -y

EXPOSE 90

CMD [ "nginix","-g","daemon off;" ]